// src/app/page.tsx
// Description: TODO

// Importing External Modules
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Importing Internal Modules
import { Header } from "../components/shared/Header";
import { Footer } from "../components/shared/Footer";
import "../sass/globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MichiBox: El kit del Gato Interior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
